#Turtle Stairs v2 By Sean Wetton 2019
from turtle import *
turtle = Turtle()
turtle.shape('turtle')
turtle.left(90)
#Start making outline
turtle.forward(90)
turtle.right(90)
turtle.forward(90)
turtle.left(90)
turtle.forward(90)
turtle.right(90)
turtle.forward(90)
turtle.left(90)
turtle.forward(90)
turtle.right(90)
turtle.forward(90)
turtle.right(90)
turtle.forward(270)
turtle.right(90)
turtle.forward(270)
#Start inside cube pattern
turtle.left(180)
turtle.forward(90)
turtle.left(90)
turtle.forward(90)
turtle.right(90)
turtle.forward(180)
turtle.left(90)
turtle.forward(90)
turtle.left(90)
turtle.forward(90)
turtle.left(90)
turtle.forward(180)
#35 lines of code, 14 less than v1!
